site_name: Sanjay's Blog
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - search.suggest
  palette:
  
    - scheme: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode
    
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Light Mode
plugins:
  - blog:
      blog_dir: .
  - search

